# Generated by Django 4.2 on 2024-08-31 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='category_name:')),
                ('category_slug', models.SlugField(max_length=250, verbose_name='slug:')),
            ],
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr_name', models.CharField(max_length=250, verbose_name='janr_name:')),
                ('janr_slug', models.SlugField(max_length=250, verbose_name='slug:')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=250, verbose_name='titile:')),
                ('published_date', models.DateField(verbose_name='date:')),
                ('description', models.TextField(max_length=250, verbose_name='description:')),
                ('actors', models.TextField(verbose_name='actors:')),
                ('country', models.CharField(max_length=250, verbose_name='country:')),
                ('image', models.ImageField(upload_to='media/posters', verbose_name='image:')),
                ('movie', models.FileField(upload_to='media/movies', verbose_name='movie_name:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_shop.category')),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_shop.janr')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='comments_date:')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_shop.movies')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
