# Generated by Django 4.2 on 2024-08-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='janr',
            options={'verbose_name': 'Janr', 'verbose_name_plural': 'Janrlar'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='titile',
            new_name='title',
        ),
    ]
